/**
 * MARI SYSTEM - ADMIN REPORT GENERATION
 * Add to admin-new.js
 */

/**
 * Generate Report Modal
 * Creates a floating modal with printable report
 */
function generateReport() {
    console.log('generateReport called');
    
    if (!applications || applications.length === 0) {
        alert('No applications to generate report.');
        return;
    }
    
    // Calculate statistics
    const total = applications.length;
    const pending = applications.filter(a => a.status === 'Pending').length;
    const approved = applications.filter(a => a.status === 'Approved').length;
    const rejected = applications.filter(a => a.status === 'Rejected').length;
    
    // Get current date and time
    const now = new Date();
    const reportDate = now.toLocaleString('en-MY', { 
        day: '2-digit', 
        month: 'long', 
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });
    
    // Determine report title based on current filters
    const urlParams = new URLSearchParams(window.location.search);
    const searchTerm = urlParams.get('search') || '';
    const filterStatus = urlParams.get('filter_status') || '';
    
    let reportTitle = "MARI Application Report";
    if (searchTerm) {
        reportTitle += " - Search: " + searchTerm;
    }
    if (filterStatus) {
        reportTitle += " - Status: " + filterStatus;
    }
    
    // Build report content
    let content = `
        <div class="modal-header" style="background: #800000; color: white; padding: 20px 25px; display: flex; justify-content: space-between; align-items: center; position: sticky; top: 0; z-index: 10;">
            <h3 style="margin: 0;">📊 ${reportTitle}</h3>
            <div style="display: flex; gap: 10px;">
                <button onclick="printReport()" class="btn-print-report" style="background: white; color: #800000; border: none; padding: 8px 16px; border-radius: 5px; cursor: pointer; font-weight: bold;">🖨️ Print</button>
                <button class="modal-close" onclick="closeModal('reportModal')" style="background: none; border: none; color: white; font-size: 1.8rem; cursor: pointer; line-height: 1;">&times;</button>
            </div>
        </div>
        <div class="modal-body" id="reportContent" style="padding: 30px;">
            
            <!-- Report Header -->
            <div style="text-align: center; border-bottom: 3px solid #800000; padding-bottom: 20px; margin-bottom: 30px;">
                <h1 style="color: #800000; font-size: 24px; margin-bottom: 10px;">${reportTitle}</h1>
                <div style="font-size: 12px; color: #666; margin-top: 10px;">
                    <p style="margin: 5px 0;">Generated on: ${reportDate}</p>
                    <p style="margin: 5px 0;">Generated by: ${sessionStorage.getItem('admin_username') || 'Admin'}</p>
                </div>
            </div>
            
            <!-- Statistics -->
            <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 30px;">
                <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; text-align: center; border-left: 4px solid #800000;">
                    <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Total Applications</div>
                    <div style="font-size: 24px; font-weight: bold; color: #333;">${total}</div>
                </div>
                <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; text-align: center; border-left: 4px solid #ffc107;">
                    <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Pending</div>
                    <div style="font-size: 24px; font-weight: bold; color: #333;">${pending}</div>
                </div>
                <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; text-align: center; border-left: 4px solid #28a745;">
                    <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Approved</div>
                    <div style="font-size: 24px; font-weight: bold; color: #333;">${approved}</div>
                </div>
                <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; text-align: center; border-left: 4px solid #dc3545;">
                    <div style="font-size: 12px; color: #666; margin-bottom: 5px;">Rejected</div>
                    <div style="font-size: 24px; font-weight: bold; color: #333;">${rejected}</div>
                </div>
            </div>
            
            <!-- Applications Table -->
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
                <thead>
                    <tr style="background: #800000; color: white;">
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">App. No.</th>
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">Applicant Name</th>
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">MyKad</th>
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">Phone</th>
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">Category</th>
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">Severity</th>
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">Submitted</th>
                        <th style="padding: 12px 8px; text-align: left; font-size: 11px;">Status</th>
                    </tr>
                </thead>
                <tbody>
    `;
    
    // Add each application row
    applications.forEach(app => {
        const submissionDate = new Date(app.submission_date);
        const formattedDate = submissionDate.toLocaleDateString('en-GB');
        
        content += `
            <tr style="border-bottom: 1px solid #e0e0e0;">
                <td style="padding: 10px 8px; font-size: 11px;">${app.application_number || 'N/A'}</td>
                <td style="padding: 10px 8px; font-size: 11px;">${app.full_name || 'N/A'}</td>
                <td style="padding: 10px 8px; font-size: 11px;">${app.mykad || 'N/A'}</td>
                <td style="padding: 10px 8px; font-size: 11px;">${app.phone_number || 'N/A'}</td>
                <td style="padding: 10px 8px; font-size: 11px;">${app.primary_category || 'N/A'}</td>
                <td style="padding: 10px 8px; font-size: 11px;">${app.severity_level || 'N/A'}</td>
                <td style="padding: 10px 8px; font-size: 11px;">${formattedDate}</td>
                <td style="padding: 10px 8px; font-size: 11px;">
                    <span style="padding: 4px 10px; border-radius: 12px; font-size: 10px; font-weight: bold; display: inline-block; background: ${getStatusColor(app.status)};">
                        ${app.status}
                    </span>
                </td>
            </tr>
        `;
    });
    
    content += `
                </tbody>
            </table>
            
            <!-- Report Footer -->
            <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; font-size: 11px; color: #666;">
                <p style="margin: 5px 0;"><strong>Malaysia Aid Registration Initiative (MARI)</strong></p>
                <p style="margin: 5px 0;">This is a computer-generated report. No signature is required.</p>
                <p style="margin: 5px 0;">&copy; ${new Date().getFullYear()} MARI System. All Rights Reserved.</p>
            </div>
        </div>
    `;
    
    // Create modal if doesn't exist
    let modal = document.getElementById('reportModal');
    if (!modal) {
        modal = document.createElement('div');
        modal.id = 'reportModal';
        modal.className = 'modal-overlay';
        modal.innerHTML = '<div class="modal-container" id="reportModalContent"></div>';
        document.body.appendChild(modal);
    }
    
    document.getElementById('reportModalContent').innerHTML = content;
    modal.classList.add('active');
}

/**
 * Get Status Badge Color
 */
function getStatusColor(status) {
    switch(status.toLowerCase()) {
        case 'pending':
            return '#fff3cd; color: #856404';
        case 'approved':
            return '#d4edda; color: #155724';
        case 'rejected':
            return '#f8d7da; color: #721c24';
        case 'under review':
            return '#cfe2ff; color: #084298';
        default:
            return '#e9ecef; color: #333';
    }
}

/**
 * Print Report
 * Opens print dialog for the report content
 */
function printReport() {
    const reportContent = document.getElementById('reportContent').innerHTML;
    const printWindow = window.open('', '_blank');
    
    printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>MARI Application Report</title>
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body { font-family: Arial, sans-serif; padding: 20px; }
                @media print {
                    body { padding: 10px; }
                    .btn-print-report { display: none; }
                }
            </style>
        </head>
        <body>
            ${reportContent}
        </body>
        </html>
    `);
    
    printWindow.document.close();
    printWindow.focus();
    
    setTimeout(() => {
        printWindow.print();
        printWindow.close();
    }, 250);
}